var weapon = {};
var $saved = $(".infoboxtable.infoboxLegendary:eq(1)");
weapon.Name = $saved.find(".infoboxname").text();
weapon.Description = $saved.find(".infoboxdescription").text().trim();
weapon.Attributes = [];
$saved.find(".infoboxfieldname").each(function($indx,$elem){
	var Attribute = {};
	Attribute.Txt = $(this).text();
	Attribute.Val = $(this).next('td').text().trim();
	weapon.Attributes.push(Attribute);
});
console.log(JSON.stringify(weapon));

/* https://fortnite.gamepedia.com/Bald_Eagle#Statistics
{"Name":"Bald Eagle","Description":"Pistol: Semi-Automatic Handcannon. Fires large rounds that deal high damage and knock back targets. Good range, accuracy, rate of fire, and magazine size.","Attributes":[{"Txt":"Damage","Val":"143"},{"Txt":"Critical Hit Chance","Val":"10%"},{"Txt":"Critical Hit Damage","Val":"+75%"},{"Txt":"Fire Rate","Val":"0.8"},{"Txt":"Magazine Size","Val":"7"},{"Txt":"Range","Val":"4096"},{"Txt":"Durability","Val":"375"},{"Txt":"Reload Time","Val":"2.2"},{"Txt":"Ammo Cost","Val":"1"},{"Txt":"Impact","Val":"675"}]}

{"Name":"Bundlebuss","Description":"Assault Weapon: Flintlock. A surprisingly accurate multi-barreled rifle that fires in powerful bursts. A high damage and large magazine help compensate for a slow fire rate and heavy kick.","Attributes":[{"Txt":"Damage","Val":"35"},{"Txt":"Critical Hit Chance","Val":"15%"},{"Txt":"Critical Hit Damage","Val":"+75%"},{"Txt":"Fire Rate","Val":"1.13"},{"Txt":"Magazine Size","Val":"24"},{"Txt":"Range","Val":"5120"},{"Txt":"Durability","Val":"375"},{"Txt":"Reload Time","Val":"3.3"},{"Txt":"Ammo Cost","Val":"1"},{"Txt":"Impact","Val":"105"}]}

{"Name":"Candy Corn LMG","Description":"Assault Weapon: Light Machine Gun - Fortnitemares. A heavy, festive weapon with a huge magazine size full of candy shaped bullets. Most effective at mid-range engagements when aiming down sights from a fixed position.","Attributes":[{"Txt":"Damage","Val":"24"},{"Txt":"Critical Hit Chance","Val":"10%"},{"Txt":"Critical Hit Damage","Val":"+50%"},{"Txt":"Fire Rate","Val":"12"},{"Txt":"Magazine Size","Val":"100"},{"Txt":"Range","Val":"4096"},{"Txt":"Headshot Multiplier","Val":"+25%"},{"Txt":"Durability","Val":"375"},{"Txt":"Reload Time","Val":"4"},{"Txt":"Ammo Cost","Val":"1"},{"Txt":"Impact","Val":"68"}]}

{"Name":"Tiger","Description":"Assault Weapon: Precision Scoped - Military. A scoped assault rifle with high headshot damage and excellent ammo efficiency at long ranges, but difficult to use up close.","Attributes":[{"Txt":"Damage","Val":"62"},{"Txt":"Critical Hit Chance","Val":"15%"},{"Txt":"Critical Hit Damage","Val":"+75%"},{"Txt":"Fire Rate","Val":"3.75"},{"Txt":"Magazine Size","Val":"15"},{"Txt":"Range","Val":"5120"},{"Txt":"Durability","Val":"375"},{"Txt":"Reload Time","Val":"3"},{"Txt":"Ammo Cost","Val":"1"},{"Txt":"Impact","Val":"143"}]}

{"Name":"Grave Digger","Description":"Assault Rifle‎: Fully Automatic. A spooky assault rifle that fires medium ammo, gaining damage and impact at the cost of accuracy and fire rate.","Attributes":[{"Txt":"Damage","Val":"30"},{"Txt":"Critical Hit Chance","Val":"5%"},{"Txt":"Critical Hit Damage","Val":"+50%"},{"Txt":"Fire Rate","Val":"8"},{"Txt":"Magazine Size","Val":"40"},{"Txt":"Range","Val":"4096"},{"Txt":"Headshot Multiplier","Val":"+50%"},{"Txt":"Durability","Val":"375"},{"Txt":"Reload Time","Val":"2.7"},{"Txt":"Ammo Cost","Val":"1"},{"Txt":"Impact","Val":"77"}]}

{"Name":"HackSAW","Description":"Light Machine Gun - Military. A lighter LMG variant with a moderate rate of fire, mild recoil, a long reload time, and overall excellent ammo efficiency. Best used when stationary, aiming down the sights, and firing in short bursts.","Attributes":[{"Txt":"Damage","Val":"28"},{"Txt":"Critical Hit Chance","Val":"5%"},{"Txt":"Critical Hit Damage","Val":"+50%"},{"Txt":"Fire Rate","Val":"10"},{"Txt":"Magazine Size","Val":"100"},{"Txt":"Range","Val":"4096"},{"Txt":"Durability","Val":"375"},{"Txt":"Reload Time","Val":"5.1"},{"Txt":"Ammo Cost","Val":"1"},{"Txt":"Impact","Val":"68"}]}

{"Name":"Hemlock","Description":"Assaultl: Medieval. Deals consistent damage to enemies at close to medium range. But falls off at longer ranges due to lower accuracy.","Attributes":[{"Txt":"Damage","Val":"26"},{"Txt":"Critical Hit Chance","Val":"15%"},{"Txt":"Critical Hit Damage","Val":"+75%"},{"Txt":"Fire Rate","Val":"11"},{"Txt":"Magazine Size","Val":"35"},{"Txt":"Range","Val":"4096"},{"Txt":"Headshot Multiplier","Val":"+25%"},{"Txt":"Durability","Val":"375"},{"Txt":"Reload Time","Val":"2.4"},{"Txt":"Ammo Cost","Val":"1"},{"Txt":"Impact","Val":"60"}]}

{"Name":"Hydra","Description":"Assault Weapon: Hydraulic. A hybrid weapon that fires a tight cluster of pellets, with considerably more knockback than an assault rifle, but better range and more focused damage than a shotgun.","Attributes":[{"Txt":"Damage","Val":"33"},{"Txt":"Critical Hit Chance","Val":"10%"},{"Txt":"Critical Hit Damage","Val":"+50%"},{"Txt":"Fire Rate","Val":"2.5"},{"Txt":"Magazine Size","Val":"10"},{"Txt":"Range","Val":"3584"},{"Txt":"Headshot Multiplier","Val":"+50%"},{"Txt":"Durability","Val":"375"},{"Txt":"Reload Time","Val":"2.7"},{"Txt":"Ammo Cost","Val":"1"},{"Txt":"Impact","Val":"102"}]}

{"Name":"Mercury LMG","Description":"Neon. A high damage light machine gun that's good for sustained fire due to the moderate rate of fire and huge magazine size. Very inaccurate when firing on the move. Deals energy damage, which is fairly effective against all types of elemental enemies.","Attributes":[{"Txt":"Damage","Val":"31"},{"Txt":"Critical Hit Chance","Val":"5%"},{"Txt":"Critical Hit Damage","Val":"+50%"},{"Txt":"Fire Rate","Val":"7.5"},{"Txt":"Magazine Size","Val":"100"},{"Txt":"Range","Val":"4096"},{"Txt":"Durability","Val":"280"},{"Txt":"Reload Time","Val":"4"},{"Txt":"Ammo Cost","Val":"1"},{"Txt":"Impact","Val":"72"}]}

{"Name":"Nailer","Description":"Assault Weapon: Hydraulic. A slow firing high impact automatic rifle with a large magazine.","Attributes":[{"Txt":"Damage","Val":"30"},{"Txt":"Critical Hit Chance","Val":"5%"},{"Txt":"Critical Hit Damage","Val":"+50%"},{"Txt":"Fire Rate","Val":"5.5"},{"Txt":"Magazine Size","Val":"40"},{"Txt":"Range","Val":"3840"},{"Txt":"Headshot Multiplier","Val":"+50%"},{"Txt":"Durability","Val":"375"},{"Txt":"Reload Time","Val":"3"},{"Txt":"Ammo Cost","Val":"1"},{"Txt":"Impact","Val":"165"}]}

{"Name":"Typewriter","Description":"Assault - Submachine Gun. Mid ranged assault weapon with a high capacity magazine and a lateral kick. Its shooting profile makes it ideal for clearing groups of nearby enemies in mobile engagements.","Attributes":[{"Txt":"Damage","Val":"27"},{"Txt":"Critical Hit Chance","Val":"10%"},{"Txt":"Critical Hit Damage","Val":"+50%"},{"Txt":"Fire Rate","Val":"9"},{"Txt":"Magazine Size","Val":"50"},{"Txt":"Range","Val":"3584"},{"Txt":"Durability","Val":"375"},{"Txt":"Reload Time","Val":"3"},{"Txt":"Ammo Cost","Val":"1"},{"Txt":"Impact","Val":"68"}]}

{"Name":"Silenced Specter","Description":"Silenced Submachine Gun - Military. Rapid fire weapon that has minimal recoil and fast aim recovery, but with less accuracy or range than most assault weapons. Equipped with a suppressor that greatly reduces distance that enemies hear gunshots.","Attributes":[{"Txt":"Damage","Val":"19"},{"Txt":"Critical Hit Chance","Val":"20%"},{"Txt":"Critical Hit Damage","Val":"+75%"},{"Txt":"Fire Rate","Val":"14.16"},{"Txt":"Magazine Size","Val":"30"},{"Txt":"Range","Val":"3584"},{"Txt":"Durability","Val":"375"},{"Txt":"Reload Time","Val":"2"},{"Txt":"Ammo Cost","Val":"1"},{"Txt":"Impact","Val":"52"}]}

{"Name":"Terminator","Description":"Assault Weapon: Light Machine Gun. A heavy weapon with high damage, an extreme rate of fire, and a huge magazine size. Very inaccurate unless aiming down sights from a fixed position, and firing in short bursts.","Attributes":[{"Txt":"Damage","Val":"24"},{"Txt":"Critical Hit Chance","Val":"10%"},{"Txt":"Critical Hit Damage","Val":"+50%"},{"Txt":"Fire Rate","Val":"12"},{"Txt":"Magazine Size","Val":"100"},{"Txt":"Range","Val":"4096"},{"Txt":"Headshot Multiplier","Val":"+25%"},{"Txt":"Durability","Val":"375"},{"Txt":"Reload Time","Val":"4"},{"Txt":"Ammo Cost","Val":"1"},{"Txt":"Impact","Val":"68"}]}

{"Name":"Wraith","Description":"Assault Weapon: Silenced - Military. A silenced assault rifle with excellent headshot damage and stability. Maintains impressive accuracy when fired in controlled bursts. Equipped with a suppressor that greatly reduces distance that enemies hear gunshots.","Attributes":[{"Txt":"Damage","Val":"30"},{"Txt":"Critical Hit Chance","Val":"20%"},{"Txt":"Critical Hit Damage","Val":"+75%"},{"Txt":"Fire Rate","Val":"7.15"},{"Txt":"Magazine Size","Val":"30"},{"Txt":"Range","Val":"5,120"},{"Txt":"Durability","Val":"375"},{"Txt":"Reload Time","Val":"2.3"},{"Txt":"Ammo Cost","Val":"1"},{"Txt":"Impact","Val":"75"}]}

{"Name":"Bolt Bolt","Description":"Pistol: Bolt Semi-Automatic. Rapidly fires high-powered bolts that can pierce through multiple enemies.","Attributes":[{"Txt":"Damage","Val":"45"},{"Txt":"Critical Hit Chance","Val":"10%"},{"Txt":"Critical Hit Damage","Val":"+75%"},{"Txt":"Fire Rate","Val":"5"},{"Txt":"Magazine Size","Val":"10"},{"Txt":"Range","Val":"3584"},{"Txt":"Headshot Multiplier","Val":"+75%"},{"Txt":"Durability","Val":"375"},{"Txt":"Reload Time","Val":"1.6"},{"Txt":"Ammo Cost","Val":"1"},{"Txt":"Impact","Val":"180"}]}

{"Name":"Whisper .45","Description":"Semi-Auto Silenced - Military. A suppressed handgun that greatly reduces the distance enemies hear and react to the shots. Harder hitting and softer shooting than the standard semi-auto pistol, but at the cost of slightly slower aim recovery and lower capacity.","Attributes":[{"Txt":"Damage","Val":"47"},{"Txt":"Critical Hit Chance","Val":"10%"},{"Txt":"Critical Hit Damage","Val":"+75%"},{"Txt":"Fire Rate","Val":"5.5"},{"Txt":"Magazine Size","Val":"12"},{"Txt":"Range","Val":"3584"},{"Txt":"Durability","Val":"375"},{"Txt":"Reload Time","Val":"2.2"},{"Txt":"Ammo Cost","Val":"1"},{"Txt":"Impact","Val":"116"}]}

{"Name":"Falcon","Description":"Pistol: Semi-Automatic Handcannon. Fires large rounds that deal high damage and knock back targets. Good range, accuracy, rate of fire, and magazine size.","Attributes":[{"Txt":"Damage","Val":"74"},{"Txt":"Critical Hit Chance","Val":"10%"},{"Txt":"Critical Hit Damage","Val":"+75%"},{"Txt":"Fire Rate","Val":"2.5"},{"Txt":"Magazine Size","Val":"8"},{"Txt":"Range","Val":"3840"},{"Txt":"Headshot Multiplier","Val":"+75%"},{"Txt":"Durability","Val":"375"},{"Txt":"Reload Time","Val":"1.8"},{"Txt":"Ammo Cost","Val":"1"},{"Txt":"Impact","Val":"353"}]}

{"Name":"Ghost Pistol","Description":"Pistol: Fortnitemares. A slow firing pistol that shoots ghostly projectiles that pass through walls and enemies.","Attributes":[{"Txt":"Damage","Val":"132"},{"Txt":"Critical Hit Chance","Val":"15%"},{"Txt":"Critical Hit Damage","Val":"+75%"},{"Txt":"Fire Rate","Val":"1.8"},{"Txt":"Magazine Size","Val":"6"},{"Txt":"Range","Val":"4500"},{"Txt":"Durability","Val":"375"},{"Txt":"Reload Time","Val":"3"},{"Txt":"Ammo Cost","Val":"1"},{"Txt":"Impact","Val":"432"}]}

{"Name":"Duelist","Description":"Pistol: Flintlock. Slow-firing revolver with a powerful kick that deals heavy headshot damage and knocks back targets. Accurate out to mid range.","Attributes":[{"Txt":"Damage","Val":"113"},{"Txt":"Critical Hit Chance","Val":"15%"},{"Txt":"Critical Hit Damage","Val":"+75%"},{"Txt":"Fire Rate","Val":"2"},{"Txt":"Magazine Size","Val":"6"},{"Txt":"Range","Val":"3840"},{"Txt":"Durability","Val":"375"},{"Txt":"Reload Time","Val":"2.4"},{"Txt":"Ammo Cost","Val":"1"},{"Txt":"Impact","Val":"450"}]}

{"Name":"Krypton Pistol","Description":"Neon. Shoots energized rounds at a rapid rate for high sustained damage. Deals energy damage, which is fairly effective against all types of elemental enemies.","Attributes":[{"Txt":"Damage","Val":"43"},{"Txt":"Critical Hit Chance","Val":"10%"},{"Txt":"Critical Hit Damage","Val":"+50%"},{"Txt":"Fire Rate","Val":"5"},{"Txt":"Magazine Size","Val":"10"},{"Txt":"Range","Val":"3584"},{"Txt":"Durability","Val":"375"},{"Txt":"Reload Time","Val":"1.6"},{"Txt":"Ammo Cost","Val":"1"},{"Txt":"Impact","Val":"94"}]}

{"Name":"Last Word","Description":"Pistol: Revolver. Mid-range revolver with a limited magazine but excellent headshot damage. Slow and precise when aiming downsights, or can be rapidly fired from the hip for a more damaging, less accurate spray of bullets.","Attributes":[{"Txt":"Damage","Val":"155"},{"Txt":"Critical Hit Chance","Val":"15%"},{"Txt":"Critical Hit Damage","Val":"+75%"},{"Txt":"Fire Rate","Val":"4.5"},{"Txt":"Magazine Size","Val":"6"},{"Txt":"Range","Val":"3840"},{"Txt":"Durability","Val":"375"},{"Txt":"Reload Time","Val":"2.3"},{"Txt":"Ammo Cost","Val":"1"},{"Txt":"Impact","Val":"619"}]}

{"Name":"Monsoon","Description":"Pistol: Special. Absurdly fast-firing pistol with a large magazine that dishes out ridiculous damage at short to mid-range. Offset by poor accuracy, extreme ammo consumption, and a brief spin-up time before firing.","Attributes":[{"Txt":"Damage","Val":"21"},{"Txt":"Critical Hit Chance","Val":"5%"},{"Txt":"Critical Hit Damage","Val":"+50%"},{"Txt":"Fire Rate","Val":"18"},{"Txt":"Magazine Size","Val":"60"},{"Txt":"Range","Val":"3840"},{"Txt":"Headshot Multiplier","Val":"+25%"},{"Txt":"Durability","Val":"375"},{"Txt":"Reload Time","Val":"3"},{"Txt":"Ammo Cost","Val":"1"},{"Txt":"Impact","Val":"36"}]}

{"Name":"Cocoa .45","Description":"Silenced Pistol: Winter. Silenced pistol with projectiles that bounce off walls and pass through enemies.","Attributes":[{"Txt":"Damage","Val":"44"},{"Txt":"Critical Hit Chance","Val":"15%"},{"Txt":"Critical Hit Damage","Val":"+75%"},{"Txt":"Fire Rate","Val":"5"},{"Txt":"Magazine Size","Val":"8"},{"Txt":"Range","Val":"5000"},{"Txt":"Durability","Val":"375"},{"Txt":"Reload Time","Val":"2.2"},{"Txt":"Ammo Cost","Val":"1"},{"Txt":"Impact","Val":"110"}]}

{"Name":"Dragon s Breath","Description":"Pistol: Special. Part double-barrel shotgun, part pistol, and part DRAGON. Fires a wide blast of pellets at close range for extreme damage and knockback. Slow to reload.","Attributes":[{"Txt":"Damage","Val":"264"},{"Txt":"Critical Hit Chance","Val":"5%"},{"Txt":"Critical Hit Damage","Val":"+50%"},{"Txt":"Fire Rate","Val":"1"},{"Txt":"Magazine Size","Val":"2"},{"Txt":"Range","Val":"2048"},{"Txt":"Durability","Val":"375"},{"Txt":"Reload Time","Val":"2.4"},{"Txt":"Ammo Cost","Val":"1"},{"Txt":"Impact","Val":"960"}]}

{"Name":"Lightning Pistol","Description":"Pistol: Fires a continuous beam that stuns, dealing great damage but at an extremely short range consuming a lot of ammo. Deals nature damage that is effective against water enemies, but weak against fire enemies.","Attributes":[{"Txt":"Damage","Val":"24"},{"Txt":"Critical Hit Chance","Val":"5%"},{"Txt":"Critical Hit Damage","Val":"+50%"},{"Txt":"Fire Rate","Val":"15"},{"Txt":"Magazine Size","Val":"40"},{"Txt":"Range","Val":"2560"},{"Txt":"Durability","Val":"375"},{"Txt":"Reload Time","Val":"2.5"},{"Txt":"Ammo Cost","Val":"1"},{"Txt":"Impact","Val":"54"}]}

*/
